apiVersion: v1
kind: ConfigMap
metadata:
  name: hook-extension
  namespace: arc-runners
data:
  container-podspec.yaml: |
    metadata:
      annotations:
        annotated-by: "extension"
      labels:
        labeled-by: "extension"
    spec:
      securityContext:
        fsGroup: 123 # Group used by GitHub default agent image    
      containers:
      - name: "$job" # Target the job container
        volumeMounts:
          - name: azurefile
            mountPath: "/.nuget/"
      volumes:
        - name: azurefile
          persistentVolumeClaim:
            claimName: azurefile