name: Container and Service Test
run-name: Run Container test workflow on ${{ inputs.arc_runner_set_name}}
on:
  workflow_dispatch: {
    inputs: {
      arc_runner_set_name: {
        description: 'The name of the Arc Runner Set',
        required: true,
        default: 'arc-runner-set'
      }
    }
  }

jobs:
  test-container-job:
    runs-on: ${{ inputs.arc_runner_set_name}}
    container: ubuntu
    steps:
      - name: test
        run: |
          echo "Hello, world!" >> $GITHUB_STEP_SUMMARY
          sleep 360
    services:
      redis:
        image: redis
        ports:
          - 6379/tcp
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 3
