trigger:
  branches:
    include:
      - 'master'
  paths:
    include:
      - .azure-pipelines/AzFilesHybrid.yml
      - AzFilesHybrid/**

pool:
  vmImage: 'windows-latest'

stages:
  - stage: Test
    displayName: 'Test AzFilesHybrid'
    jobs:
      - job: TestPowerShell5
        displayName: 'Test with PowerShell 5.1'
        steps:
          - checkout: self
          - powershell: |
              Set-Location -Path .\AzFilesHybrid
              .\init.ps1
              Test-Manifest
            displayName: 'Check .psd1 file with Test-ModuleManifest'
      - job: TestPowerShell7
        displayName: 'Test with PowerShell 7'
        steps:
          - checkout: self
          - pwsh: |
              Set-Location -Path .\AzFilesHybrid
              .\init.ps1
              Test-Manifest
            displayName: 'Check .psd1 file with Test-ModuleManifest'
  - stage: Release
    displayName: 'Release AzFilesHybrid'
    jobs:
      - job: CodeSign
        displayName: 'Sign AzFilesHybrid'
        steps:
          - checkout: none
          - task: EsrpCodeSigning@6
            displayName: 'ESRP Code Signing'
            inputs:
              ConnectedServiceName: 'AzFilesHybrid-Sign'
              AppRegistrationClientId: $(AppRegistrationClientId)
              AppRegistrationTenantId: $(AppRegistrationTenantId)
              UseMSIAuthentication: true
              AuthAKVName: $(AuthAKVName)
              AuthSignCertName: $(AuthSignCertName)
              FolderPath: 'AzFilesHybrid\AzFilesHybrid'
              signConfigType: inlineSignParams
              Pattern: '*.ps1,*.psm1,*.psd1'
              SessionTimeout: 90
              ServiceEndpointUrl: 'https://api.esrp.microsoft.com/api/v2'
              MaxConcurrency: 25
              MaxRetryAttempts: 3
              PendingAnalysisWaitTimeoutMinutes: 5
              VerboseLogin: true