name: Test RestSetAcls
on:
  push:
    paths:
      - ".github/workflows/RestSetAcls.yml"
      - "RestSetAcls/**"
  pull_request:
    paths:
      - ".github/workflows/RestSetAcls.yml"
      - "RestSetAcls/**"

jobs:
  pester-test:
    name: Pester test
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run all Pester tests
        shell: pwsh
        run: .\RestSetAcls\test.ps1
  
  test-manifest:
    name: Test .psd1 manifest file
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test .psd1 file
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
          Install-Module -Name Az -Repository PSGallery -Force -AllowClobber
          Test-ModuleManifest -Path .\RestSetAcls\RestSetAcls\RestSetAcls.psd1

  lint-with-PSScriptAnalyzer:
    name: Install and run PSScriptAnalyzer
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install PSScriptAnalyzer module
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module PSScriptAnalyzer -ErrorAction Stop
      - name: Lint with PSScriptAnalyzer
        shell: pwsh
        run: |
          Invoke-ScriptAnalyzer -Path .\RestSetAcls -Severity Warning -Recurse -Outvariable issues
          $errors   = $issues.Where({$_.Severity -eq 'Error'})
          $warnings = $issues.Where({$_.Severity -eq 'Warning'})
          if ($errors) {
              Write-Error "There were $($errors.Count) errors and $($warnings.Count) warnings total." -ErrorAction Stop
          } else {
              Write-Output "There were $($errors.Count) errors and $($warnings.Count) warnings total."
          }
