name: Test RestSetAcls
on:
  push:
    paths:
      - ".github/workflows/RestSetAcls.yml"
      - "RestSetAcls/**"
  pull_request:
    paths:
      - ".github/workflows/RestSetAcls.yml"
      - "RestSetAcls/**"

jobs:
  pester-test:
    name: Pester test on PowerShell 7
    runs-on: windows-latest
    defaults:
      run:
        working-directory: .\RestSetAcls
        shell: pwsh
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Print PowerShell version
        run: $PSVersionTable
      - name: Run all Pester tests
        run: |
          .\init.ps1
          Test

  pester-test-powershell-5:
    name: Pester test on PowerShell 5.1
    runs-on: windows-latest
    defaults:
      run:
        working-directory: .\RestSetAcls
        shell: powershell
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Print PowerShell version
        run: $PSVersionTable
      - name: Run all Pester tests
        run: |
          .\init.ps1
          Test

  test-format:
    name: Check PowerShell formatting
    runs-on: windows-latest
    defaults:
      run:
        working-directory: .\RestSetAcls
        shell: pwsh
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Test PowerShell formatting
        run: |
          .\init.ps1
          Test-Format

  Check-manifest:
    name: Check .psd1 manifest file
    runs-on: windows-latest
    defaults:
      run:
        working-directory: .\RestSetAcls
        shell: pwsh
    steps:
      - uses: actions/checkout@v4
      - name: Check .psd1 file with Test-ModuleManifest
        run: |
          .\init.ps1
          Test-Manifest

  lint:
    name: Lint in PowerShell 7
    runs-on: windows-latest
    defaults:
      run:
        working-directory: .\RestSetAcls
        shell: pwsh
    steps:
      - uses: actions/checkout@v4
      - name: Lint with PSScriptAnalyzer
        run: |
          .\init.ps1
          Lint
  
  lint-powershell-5:
    name: Lint in PowerShell 5.1
    runs-on: windows-latest
    defaults:
      run:
        working-directory: .\RestSetAcls
        shell: powershell
    steps:
      - uses: actions/checkout@v4
      - name: Lint with PSScriptAnalyzer
        run: |
          .\init.ps1
          Lint
